name: hint
# run the workflow every morning
# or when we trigger the workflow manually
on:
  workflow_dispatch:
    inputs:
      email:
        description: Email to send the hint to
        type: string
        default: ''
        required: false
      hints:
        description: Number of letters to reveal
        type: integer
        default: 1
  schedule:
    # UTC time
    - cron: '0 7 * * *'
jobs:
  hint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Print GitHub variables 🖨
        run: npx @bahmutov/print-env GITHUB

      - name: Echo env variables
        run: echo "run ID and run attempt ${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}"

      - name: Export CI build id 📤
        run: echo ::set-output name=ci_build_id::${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}
        id: export-ci-build-id

      - name: Cypress run 🧪
        #  https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v2
        with:
          spec: 'cypress/integration/email-hint.js'
          env: 'hints=${{ github.event.inputs.hints }}'
          record: true
          group: 'hint'
          tag: 'hint'
          ci-build-id: ${{ steps.export-ci-build-id.outputs.ci_build_id }}
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SENDGRID_FROM: ${{ secrets.SENDGRID_FROM }}
          WORDLE_HINT_EMAIL: ${{ github.event.inputs.email || secrets.WORDLE_HINT_EMAIL }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          DEBUG: '@cypress/github-action'
