name: hint
# run the workflow every day at 5 am
# or when we trigger the workflow manually
on:
  workflow_dispatch:
    inputs:
      email:
        description: Email to send the hint to
        type: string
        default: ${{ secrets.WORDLE_HINT_EMAIL }}
        required: false
  schedule:
    - cron: '0 5 * * *'
jobs:
  hint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Cypress run 🧪
        #  https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v2
        with:
          spec: 'cypress/integration/email-hint.js'
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SENDGRID_FROM: ${{ secrets.SENDGRID_FROM }}
          WORDLE_HINT_EMAIL: ${{ inputs.email }}
